In [1]:
import pandas as pd
import numpy as np
import sys
import os
import matplotlib.pyplot as plt
sys.path.append(os.path.abspath(os.path.dirname("./")))

In [2]:
ROOT_PATH = os.path.dirname(os.path.abspath("./"))
ROOT_PATH

'd:\\PSE\\博兴京博\\New'

In [3]:
df = pd.read_parquet(f"{ROOT_PATH}\\data\\data_tot.parquet")
df

,time,卤化工段胶液总量2,反应溴添加量,储罐胶浓在线检测,R510A温度,R511A温度,R512A温度,R510B温度,R511B温度,R512B温度,硬脂酸钙加注量,ESBO加注量,中和碱液添加量,R513温度,R514温度
0,2024-01-20 03:34:00,NaN,NaN,21.0555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-20 03:35:00,NaN,NaN,21.0621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-20 03:36:00,NaN,NaN,21.0687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-20 03:37:00,51509.2500,NaN,21.0711,NaN,NaN,NaN,15.6219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-20 03:38:00,51484.3984,NaN,21.0641,NaN,NaN,NaN,15.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936840,2025-10-31 23:56:00,NaN,0.0112,NaN,NaN,NaN,16.6920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936841,2025-10-31 23:57:00,NaN,0.0112,NaN,NaN,NaN,16.6821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936842,2025-10-31 23:58:00,NaN,0.0112,NaN,NaN,NaN,16.6779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936843,2025-10-31 23:59:00,NaN,0.0112,NaN,NaN,NaN,16.6779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936844,2025-11-01 00:00:00,NaN,0.0112,NaN,NaN,NaN,16.6618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.isnull().sum()

time              0
卤化工段胶液总量2     11132
反应溴添加量         7127
储罐胶浓在线检测       7146
R510A温度        5835
R511A温度        8744
R512A温度        5818
R510B温度       13825
R511B温度       11288
R512B温度        6334
硬脂酸钙加注量        9529
ESBO加注量        6564
中和碱液添加量        9235
R513温度         8100
R514温度       124131
dtype: int64

In [5]:
map_list = {
    "卤化工段胶液总量2": [30000, 65000],
    "反应溴添加量": [200,500],
    "储罐胶浓在线检测": [13,25],
    "R510A温度": [38, 46],
    "R511A温度": [19,25],
    "R512A温度": [39,54],
    "R510B温度": [15, 40],
    "R511B温度": [35, 45],
    "R512B温度": [40, 55],
    "硬脂酸钙加注量": [700, 1300],
    "ESBO加注量": [100, 170],
    "中和碱液添加量": [2700, 7000],
    "R513温度": [40, 55],
    "R514温度": [40, 55]
}

def get_map_safe(df: pd.DataFrame, col_name: str, map_list: dict) -> pd.DataFrame:
    """
    清洗界外值：强校验数据类型，并将低于下限与高于上限的值记为np.nan
    """
    # 1. 强制转换为浮点数，将无法解析的异常字符串自动转为 NaN（防 Object 陷阱）
    df[col_name] = pd.to_numeric(df[col_name], errors='coerce')
    
    # 2. 获取阈值
    lower, upper = map_list[col_name]
    
    # 3. 边界过滤
    df.loc[df[col_name] < lower, col_name] = np.nan
    df.loc[df[col_name] > upper, col_name] = np.nan

    return df

In [6]:
df = df.set_index("time")
df

,卤化工段胶液总量2,反应溴添加量,储罐胶浓在线检测,R510A温度,R511A温度,R512A温度,R510B温度,R511B温度,R512B温度,硬脂酸钙加注量,ESBO加注量,中和碱液添加量,R513温度,R514温度
time,,,,,,,,,,,,,,
2024-01-20 03:34:00,NaN,NaN,21.0555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:35:00,NaN,NaN,21.0621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:36:00,NaN,NaN,21.0687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:37:00,51509.2500,NaN,21.0711,NaN,NaN,NaN,15.6219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:38:00,51484.3984,NaN,21.0641,NaN,NaN,NaN,15.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-31 23:56:00,NaN,0.0112,NaN,NaN,NaN,16.6920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10-31 23:57:00,NaN,0.0112,NaN,NaN,NaN,16.6821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10-31 23:58:00,NaN,0.0112,NaN,NaN,NaN,16.6779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10-31 23:59:00,NaN,0.0112,NaN,NaN,NaN,16.6779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11-01 00:00:00,NaN,0.0112,NaN,NaN,NaN,16.6618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
def apply_global_map(df: pd.DataFrame, map_dict: dict) -> pd.DataFrame:
    """
    遍历 DataFrame 所有列，将超出 map_dict 边界的值置为 NaN
    """
    # 建立副本，彻底阻断 SettingWithCopyWarning 及底层数据污染
    df_clean = df.copy()
    
    # 仅遍历存在于规则字典中的列，实现解耦
    for col in df_clean.columns:
        if col in map_dict:
            # 1. 强转为数值型，规避隐式 Object 字符串比较陷阱
            df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
            
            # 2. 提取上下限
            lower, upper = map_dict[col]
            
            # 3. 向量化掩码操作：超出边界的布尔矩阵为 True，mask 会自动将其替换为 NaN
            outlier_condition = (df_clean[col] < lower) | (df_clean[col] > upper)
            df_clean[col] = df_clean[col].mask(outlier_condition)
            
    return df_clean
df_cleaned = apply_global_map(df, map_list)

# 查看清洗后的结果
display(df_cleaned.head())

,卤化工段胶液总量2,反应溴添加量,储罐胶浓在线检测,R510A温度,R511A温度,R512A温度,R510B温度,R511B温度,R512B温度,硬脂酸钙加注量,ESBO加注量,中和碱液添加量,R513温度,R514温度
time,,,,,,,,,,,,,,
2024-01-20 03:34:00,NaN,NaN,21.0555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:35:00,NaN,NaN,21.0621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:36:00,NaN,NaN,21.0687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:37:00,51509.2500,NaN,21.0711,NaN,NaN,NaN,15.6219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-01-20 03:38:00,51484.3984,NaN,21.0641,NaN,NaN,NaN,15.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_cleaned.isnull().sum()

卤化工段胶液总量2     89335
反应溴添加量       173818
储罐胶浓在线检测      50356
R510A温度      285315
R511A温度      286930
R512A温度      281448
R510B温度       48014
R511B温度      801524
R512B温度      781368
硬脂酸钙加注量      154826
ESBO加注量      182959
中和碱液添加量      210603
R513温度       143672
R514温度       204447
dtype: int64

In [9]:
df_new = pd.read_parquet(f"{ROOT_PATH}\\data\\data_new.parquet")
df_new

,time,卤化工段胶液总量2,反应溴添加量,储罐胶浓在线检测,R510A温度,R511A温度,R512A温度,R510B温度,R511B温度,R512B温度,硬脂酸钙加注量,ESBO加注量,中和碱液添加量,R513温度,R514温度
0,2024-01-20 03:34:00,NaN,NaN,21.0555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-01-20 03:35:00,NaN,NaN,21.0621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-01-20 03:36:00,NaN,NaN,21.0687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-01-20 03:37:00,51509.2500,NaN,21.0711,NaN,NaN,NaN,15.6219,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-01-20 03:38:00,51484.3984,NaN,21.0641,NaN,NaN,NaN,15.6038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936840,2025-10-31 23:56:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936841,2025-10-31 23:57:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936842,2025-10-31 23:58:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936843,2025-10-31 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
936844,2025-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_new.isnull().sum()

time              0
卤化工段胶液总量2     89335
反应溴添加量       173818
储罐胶浓在线检测      50356
R510A温度      285315
R511A温度      286930
R512A温度      281448
R510B温度       48014
R511B温度      801524
R512B温度      781368
硬脂酸钙加注量      154826
ESBO加注量      182959
中和碱液添加量      210603
R513温度       143672
R514温度       204447
dtype: int64

## 7.2之前的数据删除